### ISSUE TITLE
Data Science: Minor Issues

### ISSUE THREAD

**Issue by minhtumn** [bitprj/BitUniversity#41]
# Week 1 - Introduction to Digital History

- [x] Mistake: “discussion and research on about related topics” - I think this is unintentionally repetitive
Location: About this course

- [x] Mistake: “Additionally, you will also have access to homeworks for the 7 Tutorials, these homeworks will be similar to the 'Now Try This' sections.” - punctuation error
Location: “Homeworks”

- [x] Mistake: Maybe use a different term for “practicum” or define it
Location: Practicums

- [x] Mistake: “The reason a field such as data analysis is very important is because, in many cases” - punctuation
Location: What is Data Science and Analytics?

- [x] Mistake:  “cholera was transmitted by “an agent in the water” than by the accepted theory” - add “rather”
Location: What is Data Science and Analytics?

# Week 2: Introduction to Python

- [x] Mistake: “we can do a lot more with Python” - capitalization
Location: Variable Assignments

- [x] Mistake: “wrapped it up with learning” - replace “with” with “by”
Location: Variable Assignments

- [x] Mistake: “Python comes with booleans” - clarify phrase “comes with”
Location: Booleans

- [x] Mistake: “That's all to booleans!” - replace “to” with “for”
Location: Booleans

- [x] Mistake: “Earlier when discussing strings we introduced the concept of a sequence” - add comma after “strings”
Location: Lists

- [x] Mistake: “Lists in Python however,” - add comma after “Python”
Location: Lists: Basic List Methods

- [x] Mistake: “By default pop takes off the last index” - add comma after “default”
Location: Lists: Basic List Methods

- [x] Mistake: “but now there are two levels for the index. The items in the matrix object, and then the items inside that list!” - replace period with a colon, remove comma, remove “then”
Location: Lists: Nesting Lists

- [x] Mistake: “In Python tuples are very similar to lists, however, unlike lists they are immutable meaning they can not be changed” - “In Python, tuples are very similar to lists. However, unlike lists, they are immutable— meaning they cannot be changed.” might be easier to digest
Location: Tuples

- [x] Mistake: “You'll have an intuition of how to use tuples” - awkward phrasing
Location:  Tuples

**Comment by jrainbolt** [comment]
Mistake: "Note: 'macdonald'.capitalize() returns 'Macdonald'" - the 4rth letter in the return word should be capitalized, so 'MacDonald' 
Location: 5.0 Now Try This
